CREATE TABLE IF NOT EXISTS admin_user (
id SERIAL PRIMARY KEY NOT NULL,
email CHAR(255) NOT NULL,
password CHAR(255) NOT NULL,
dateupdated TIMESTAMP NOT NULL,
datecreated TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS admin_user_session (
session_id VARCHAR(36) PRIMARY KEY NOT NULL,
admin_user INTEGER UNIQUE REFERENCES admin_user,
expiry_date TIMESTAMP NOT NULL,
datecreated TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS page (
id SERIAL PRIMARY KEY NOT NULL,
title VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL UNIQUE,
teaser VARCHAR(255),
content TEXT,
dateupdated TIMESTAMP NOT NULL,
datecreated TIMESTAMP NOT NULL);